version: 0.2

phases:
  pre_build:
    commands:
      - aws ecr get-login-password --region ap-southeast-1 | docker login --username AWS --password-stdin 576174293178.dkr.ecr.ap-southeast-1.amazonaws.com
      - REPOSITORY_URI=576174293178.dkr.ecr.ap-southeast-1.amazonaws.com/notification-service
      - IMAGE_TAG=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
  build:
    commands:
      - docker build -t $REPOSITORY_URI:$IMAGE_TAG .
      - docker tag $REPOSITORY_URI:$IMAGE_TAG $REPOSITORY_URI:latest
  post_build:
    commands:
      - docker push $REPOSITORY_URI:$IMAGE_TAG
      - docker push $REPOSITORY_URI:latest
      - sed -i "s|<IMAGE_URI>|$REPOSITORY_URI:$IMAGE_TAG|g" notification-service.yaml
      - kubectl apply -f notification-service.yaml
      - npm install
      - npm run test
artifacts:
  files:
    - notification-service.yaml
