version: 0.2

env:
  variables:
    AWS_REGION: ap-southeast-1
    ACCOUNT_ID: 576174293178

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com
      - IMAGE_TAG=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - if [ -z "$IMAGE_TAG" ]; then IMAGE_TAG=latest; fi

  build:
    commands:
      - |
        for service in agent-service integration-service notification-service aggregator-service; do
          echo "Building $service..."
          REPO="$ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$service"
          docker build -t $REPO:$IMAGE_TAG ./$service
          docker tag $REPO:$IMAGE_TAG $REPO:latest
        done

  post_build:
    commands:
      - |
        for service in agent-service integration-service notification-service aggregator-service; do
          echo "Pushing $service..."
          REPO="$ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$service"
          docker push $REPO:$IMAGE_TAG
          docker push $REPO:latest
        done
      - echo All images built and pushed successfully.

artifacts:
  files:
    - '**/*'
