version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws --version
      - aws ecr get-login-password --region ap-southeast-1 | docker login --username AWS --password-stdin 576174293178.dkr.ecr.ap-southeast-1.amazonaws.com
      - REPOSITORY_URI=576174293178.dkr.ecr.ap-southeast-1.amazonaws.com/agent-service
      - IMAGE_TAG=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
  build:
    commands:
      - echo Building Docker image...
      - docker build -t $REPOSITORY_URI:$IMAGE_TAG .
      - docker tag $REPOSITORY_URI:$IMAGE_TAG $REPOSITORY_URI:latest
  post_build:
    commands:
      - echo Pushing Docker image...
      - docker push $REPOSITORY_URI:$IMAGE_TAG
      - docker push $REPOSITORY_URI:latest
      - echo Writing Kubernetes manifest...
      - sed -i "s|<IMAGE_URI>|$REPOSITORY_URI:$IMAGE_TAG|g" agent-service.yaml
      - echo Deploying to EKS...
      - kubectl apply -f agent-service.yaml
      - echo Running integration tests...
      - npm install
      - npm run test
artifacts:
  files:
    - agent-service.yaml
