# aggregator-cronjob.yaml
apiVersion: batch/v1
kind: CronJob
metadata:
  name: aggregator-job
spec:
  schedule: "0 * * * *"  # Runs every hour
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: aggregator
            image: 576174293178.dkr.ecr.ap-southeast-1.amazonaws.com/aggregator-service:latest
            args: ["python", "app.py"]
          restartPolicy: OnFailure
