# integration-service.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: integration-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: integration
  template:
    metadata:
      labels:
        app: integration
    spec:
      containers:
      - name: integration
        image: 576174293178.dkr.ecr.ap-southeast-1.amazonaws.com/integration-service:latest
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: integration-service
spec:
  selector:
    app: integration
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: ClusterIP
